M48
; DRILL file {KiCad 9.0.4} date 2025-11-17T00:45:14-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-17T00:45:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.700
%
G90
G05
T1
X98.5Y-61.0
T2
X64.5Y-134.5
X187.65Y-60.5
T3
X147.5Y-136.5
T4
X228.5Y-135.0
M30
