M48
; DRILL file {KiCad 9.0.4} date 2025-11-17T00:45:14-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-17T00:45:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
%
G90
G05
T1
X59.5Y-73.0
X100.0Y-155.5
X186.0Y-155.0
X229.0Y-77.5
X241.5Y-106.5
M30
